### ISSUE TITLE
Android Studio 3 :  Failed to resolve "com.github.mrmike:Ok2Curl:0.4.5"

### ISSUE THREAD

**Issue by Abdul-Hannan** [mrmike/Ok2Curl#45]
as described in README,

added it to dependencies
`compile "com.github.mrmike:Ok2Curl:0.4.5"`

jcenter() is there in the repository list and also in the buildScript list

**Comment by mrmike** [comment]
Hi @Abdul-Hannan 

I think it's happening because of the typo in README file. I've already prepared a fix for that: https://github.com/mrmike/Ok2Curl/pull/46. Cause library is available on jcenter(as you can see [here](https://jcenter.bintray.com/com/github/mrmike/ok2curl/0.4.5/)).

Instead of using `com.github.mrmike:Ok2Curl:0.4.5` use `com.github.mrmike:ok2curl:0.4.5` (no uppercased letters).

Thanks
